### ISSUE TITLE
Please add armhf binaries

### ISSUE THREAD

**Issue by mbirth** [shaggytwodope/drivedebpackage#2]
I noticed the PPA is missing binaries for armhf architecture (e.g. Raspberry Pi). Could you add them, please?

**Comment by shaggytwodope** [comment]
@mbirth I feel like such an idiot for not responding to you sooner. Yes they are now enabled, https://launchpadlibrarian.net/242686736/buildlog_ubuntu-wily-armhf.drive_0.3.5-0_BUILDING.txt.gz

Should be able to use them for any version of ubuntu on arm, if you have any issues feel free to hit me up. (spam email even lol)
